syntax = "proto3";

package server.ingress.loyalty.v1;

import "protoc-gen-openapiv2/options/annotations.proto";

option go_package = "github.com/stashgg/public-api/gen/proto/server/ingress/loyalty/v1";

enum LoyaltyRewardType {
  option (grpc.gateway.protoc_gen_openapiv2.options.openapiv2_enum) = {description: "The kind of reward granted at a loyalty milestone."};
  LOYALTY_REWARD_TYPE_UNSPECIFIED = 0;
  LOYALTY_REWARD_TYPE_IN_GAME_CURRENCY = 1;
  LOYALTY_REWARD_TYPE_LOYALTY_CURRENCY = 2;
  LOYALTY_REWARD_TYPE_LOYALTY_POINTS = 3;
  LOYALTY_REWARD_TYPE_SKU_ITEM = 4;
}
